{
    'name': 'Imports Vefase',
    'summary': 'Modulo de Importaciones para Vefase',
    'category': 'Sales/CRM',
    'author': ['Alejandro Yende <alyendedev@gmail.com>',
                'Gabriel Antunez <antunezgabrielc32@gmail.com>'],
    'version': '17.0.0.0.0',
    'license': 'LGPL-3',
    'depends': ['base',
                'account_accountant',
                'contacts',
                'stock'],
    'data': [
        'security/ir.model.access.csv',
        'views/imports_views.xml',
        'views/res_partner_views.xml',
        'views/imports_kanban_views.xml',
        'views/company_views.xml',
        'views/container_views.xml',
        'views/size_parameter_views.xml',
        'views/checklist_views.xml',
        'views/expenses_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
